### ISSUE TITLE
New entailments/relations

### ISSUE THREAD

**Issue by mbuit82** [benbrastmckie/ModelChecker#12]
Hey Ben,

I was trying out the new relations, and I think I have a grasp on how the work loosely. I got a model (as desired) for the second one (top-bottom from those in the TODOs), but I also got a model for the third one (which I don't think should be giving a model). Can you check to make sure those are looking right? Also, I think I found a typo on `cf_excl_mid.py`—should lines 73, 74, and 78 have `t` instead of where they currently have `s`?

**Comment by benbrastmckie** [comment]
This has been resolved.
