### ISSUE TITLE
Top Elements and Modals

### ISSUE THREAD

**Issue by benbrastmckie** [benbrastmckie/ModelChecker#22]
I think this is an easy issue to fix, but can't quite figure it out. In the `add_top_nec` branch, I was trying to add a designated top element `\\top` to the language along with a model constraint that makes every state verify `\\top` and no state falsify `\\top`. Officially this is a zero-place operator which has the same type as a sentence letter but has a fixed interpretation (it is always verified by everything and falsified by nothing). This is what I came up with:
```
    def find_model_constraints(prefix_sentences, sentence_letters):
        """find constraints corresponding to the input sentences"""
        Const('\\top', AtomSort)
        x = BitVec("top_dummy_x", N)
        y = BitVec("top_dummy_y", N)
        top_constraints = [ForAll(x, verify(x, '\\top')), ForAll(y, Not(falsify(y, '\\top')))]
        for const in prop_const('\\top'):
            top_constraints.append(const)
        prop_constraints = []
        for sent_letter in sentence_letters:
            for const in prop_const(sent_letter):
                prop_constraints.append(const)
        input_constraints = []
        for sentence in prefix_sentences:
            sentence_constraint = true_at(sentence, w)
            input_constraints.append(sentence_constraint)
        model_constraints = top_constraints + prop_constraints + input_constraints
        return model_constraints
```
Unfortunately I couldn't figure out how to debug this. If @mbuit82 get a chance to try to debug this I am curious to test out the results. This is definitely lower priority than the `print_props` algorithm but could be interesting.

Adding the top element is of interest because it will allow us to define modal operators. In particular `\\Box A := \\top \boxright A` which says that `A` is necessary just in case `A` would be the case if anything (i.e., `\\top`) were the case. Another approach would be to add `\\top` as an operator along with a semantic clause which makes every state verify `\\top` and no state falsify `\\top`, but this should amount to the same thing, and so figured it would be best to cut to the chase by directly including the Z3 constraints for `\\top`.

**Comment by mbuit82** [comment]
Hey Ben, I think top is working now. There is a file called top test that has the test we were working with yesterday and some other basic tests. Basically since `true_at` is only evaluated for input sentences and `\\top` was not an input sentence, it was never being triggered where we put it. The constraint is now in `find_model_constraints`.

**Comment by benbrastmckie** [comment]
Awesome! Looks great. I ended up removing the following from `true_at` since I agree that it is not needed:
```
            if 'top' in str(sent)[0]:
                raise ValueError('This is raised in principle when top is a proposition. @B, what should we do?')
```
I ran tests and it looks like it validates an S5 modal logic which is just what it should do. The entailments are included at the end of the valid tests in `examples`. So `top` is working great.

Although the modal operators are definable in terms of `top` (i.e., `\\Box A` = `\\top \boxright A` and `\\Diamond A` = `\\neg \\Box \\neg A`), it would be nice to include the modal operators for ease of use. It's not a high priority, but something I'll add to the TODOs.

**Comment by mbuit82** [comment]
Sounds good! I'll get to work on that!

**Comment by mbuit82** [comment]
It wouldn't be hard at all—I'm thinking we could actually, before doing _anything_ to the prefix input sentence, substitute instances of `\\Box A` with `\\top \\boxright A` (and same for `\\Diamond A`). Let me know if that sounds reasonable, or if you'd prefer there to be semantic clauses for these. The advantage of this idea is ease of implementation. The drawback (which may be pretty bad tbh) is that the printed infix forms would have `\\boxright` and not the modal operators. Though possibly in the `Infix` function it may be possible to make something so that if there is an instance of `\\top \\boxright A`, replace it with `\\box` (likewise for `\\Diamond`). Let me know what you think about the idea—if you prefer semantic clauses though, we can also pursue that route instead.

**Comment by benbrastmckie** [comment]
I also thought about substitution but the printing is a problem. Also there are some upshots to adding the semantic clause since we could then use the semantics to prove that `\\Box A` is equivalent to `(\\top \\boxright A)` which is sorta cool. The semantic proof is not hard, but it's a plus. The real issue is the printing.

**Comment by mbuit82** [comment]
Sounds good! What would the semantic clauses for the two of them look like?

**Comment by benbrastmckie** [comment]
There are different ways to do it, but here is one good option:

- `\\Box A` is true at a world `w` just in case the `A`-alternatives to `w` include all worlds.
- `\\Diamond A` is true at world `w` just in case the `A`-alternatives to `w` include at least one world.

The other way to go is to avoid alternatives entirely:

- `\\Box A` is true at a world `w` just in case every possible state is compatible with a verifier for `A`.
- `\\Diamond A` is true at world `w` just in case there is a possible state that verifies `A`.

These should amount to the same thing. The latter may have better performance since they avoid the alternatives definition which is complicated. The latter are also definitionally further from the semantics to result from `\\top \\boxright A`, so that's another reason to prefer the latter. Let me know if you hit any snags.

**Comment by mbuit82** [comment]
Sounds good—just in case I'm reading this right, does this mean `\\Box (A \\boxright B)` is not well-formed? Since `(A \\boxright B)` doesn't have verifiers, it has words that it's true at (or are those the same as the verifiers for a counterfactual?)

**Comment by benbrastmckie** [comment]
Shoots your right! That's a good reason to prefer the first clauses. Or simpler is:

- \\Box A is true in w iff A is true in every world 
- \\Diamond A is true in w iff A is true in some world 

Then A can be any sentence. Should run fast too.

**Comment by mbuit82** [comment]
Sounds good! They've been proving to pose quite the challenge actually lol. I have a question for you though before I can keep on going much with the modals—should we treat modals as Propositions (ie, do they have anything that intuitively corresponds with verifiers and falsifiers, like counterfactuals do? It seems to me that for `box` sentences the "verifiers" should be all worlds and for `diamond` sentences the verifiers should be all worlds also. Then again I know next to nothing about modal logic so)

**Comment by benbrastmckie** [comment]
Yes that is the right idea. I added some notes also copied below:
```
        if 'iamond' in op:
            # NOTE: if there is any world where the argument Y is true, then
            # Y_V is the set of all worlds and Y_F is empty. If Y is false in
            # every world, then Y_F is the set of all worlds and Y_V is empty
            DIAMOND
        if 'ox' in op:
            # NOTE: if the argument Y is true in every world, then
            # Y_V is the set of all worlds and Y_F is empty. If Y is false in
            # any world, then Y_F is the set of all worlds and Y_V is empty
            BOX
```
I noticed that `iamond` was used in place of `Diamond`. Is this because `D` is a sentence letter?

**Comment by mbuit82** [comment]
Sounds good! I put `iamond` in in case the input has a lowercase D. This way it can capture `\\diamond A` and `\\Diamond A` as "possibly A". But it can be changed to just capital D also

**Comment by mbuit82** [comment]
Ah yes true about box and boxright—I'll make those changes!

**Comment by benbrastmckie** [comment]
I think these changes should happen in a branch to protect master. That way master continues to work. Seems like things broke with the last push.

**Comment by benbrastmckie** [comment]
Ok I found the function that was causing the trouble `evaluate_modal_expr` in `model_structure`. I created a branch called `add_modals`. I'll also created a branch `fix_print` which I'm going to work on to get the formatting working.

**Comment by mbuit82** [comment]
I just pushed to master and I think it's working on my end, let me know if that's not the case for you!

**Comment by mbuit82** [comment]
Here's a case that I'm not sure is fully working: 
```There is a 3-model of:

(\Box A \vee \Box B)
\neg (A \wedge B)

Possible states:
  #b000 = □
  #b001 = a
  #b010 = b
  #b100 = c
  #b101 = a.c (world)
  #b110 = b.c (world)

The evaluation world is a.c:
  B  (true in a.c)
  A  (not true in a.c)

[[A], [B], ['\\neg', ['\\wedge', [A], [B]]], ['\\wedge', [A], [B]]]
  |A| = < {b.c}, {a} >
  A-alternatives to a.c = {b.c}
    (A \wedge B), A, B are true in b.c
    \neg (A \wedge B) is not true in b.c

  |B| = < {a, a.c, c}, ∅ >
  B-alternatives to a.c = {a.c}
    B, \neg (A \wedge B) are true in a.c
    (A \wedge B), A are not true in a.c

  |\neg (A \wedge B)| = < {a}, {b.c} >
  \neg (A \wedge B)-alternatives to a.c = {a.c}
    B, \neg (A \wedge B) are true in a.c
    (A \wedge B), A are not true in a.c

  |(A \wedge B)| = < {b.c}, {a} >
  (A \wedge B)-alternatives to a.c = {b.c}
    (A \wedge B), A, B are true in b.c
    \neg (A \wedge B) is not true in b.c

(\Box A \vee \Box B) is False in a.c:
  \Box A is False in a.c:
A is False in world a
  \Box B is False in a.c:

\neg (A \wedge B) is True in a.c:
  (A \wedge B) is False in a.c:
    A is False in world a.c
    B is True in world a.c```

It's finding a model (as—I think—it should) but the model doesn't look right. It looks like `B` is neither true nor false at world `b.c`. This makes the model say that `\\Box B` is False (as I think it should be). But when prompted to give reasons for that (in `rec_print`) it's blank because `B` has no falsifiers (and more relevantly doesn't have a truth value at `b.c`. Is this related to the exhaustivity problem?

**Comment by benbrastmckie** [comment]
I agree that something is wrong. It looks like `B` is true in all worlds and so necessary, and yet it says that `\\Box B` is false in `a.c`. It is also strange that it says that A is false in `a` when `a` is not a world. That line is also not indented so something must be up there. Otherwise it looks pretty good. Given that `\\Box B` should be true and `A` is false at the evaluation world, this shouldn't be a countermodel at all.

I tried to get the model to run but hit some more errors. I tried to find them but didn't come up with much:
```
  File "/home/benjamin/Documents/Philosophy/Projects/ModelChecker/model_checke
r/package/model_structure.py", line 479, in print_inputs_recursively
    self.rec_print(input_prop, initial_eval_world, output)
  File "/home/benjamin/Documents/Philosophy/Projects/ModelChecker/model_checke
r/package/model_structure.py", line 470, in rec_print
    self.rec_print(left_subprop, current_world, output, indent_num)
  File "/home/benjamin/Documents/Philosophy/Projects/ModelChecker/model_checke
r/package/model_structure.py", line 441, in rec_print
    self.rec_print(first_subprop, u)
TypeError: ModelStructure.rec_print() missing 1 required positional argument: 
'output'
```

**Comment by benbrastmckie** [comment]
It seems like it might be taking worlds to be states. This could happen from assigning modal propositions to sets of worlds in which they are true. That is a good thing to do (same as assigning counterfactuals to sets of worlds), but then it is important that in considering complex propositions with modals in them that we don't use product or coproduct. So I think the issue is in `find_complex_proposition`. Note that this would have come up if we were to disjoin counterfactuals as well. 

I think what may be required is to divide `find_complex_proposition` into an extensional and non-extensional cases. The product/coproduct stuff can only occur in the extensional cases.

Another strategy which may be easier to implement is to take the null state to verify non-extensional sentences (modals and counterfactuals) when they are true, and to falsify them otherwise. This would simplify the syntax since then we wouldn't need to divide the `find_complex_proposition` function. The semantics should be able to stay the same.

One other question: I noticed that 'Box' gets included under the `leg(complex_sentence) == 2` case in `find_complex_proposition`. I'm not sure what the reasons if for that. It should be a unary operator like 'Diamond' and 'neg'. This might also be a related issue.

**Comment by benbrastmckie** [comment]
What do you think about the following:
```
        if 'Box' in op:
            if not self.evaluate_modal_expr(complex_sentence):
                return (set(), set(self.world_bits))
            return (set(self.world_bits), set())
        if 'Diamond' in op:
            if self.evaluate_modal_expr(complex_sentence):
                return (set(self.world_bits), set())
            return (set(), set(self.world_bits))
```

**Comment by mbuit82** [comment]
looks good to me! (By the way, I changed the order of the methods in ModelStructure to make them more intuitive, which I think may affect you if you're working on master, sorry)

**Comment by benbrastmckie** [comment]
seems to be working! I just pushed the changes mentioned above.

**Comment by mbuit82** [comment]
And the things you mentioned about `find_complex_proposition` make sense—making two `find_complex_proposition` functions would be—I agree—the ideal thing to do (since as we've talked we really shouldn't be treating CFs as having verifiers in the first place) but would take a while. It would be good to do in the long run and for clarity I think, but for now the null state solution sounds good. 

And the `len == 2` is a renmant from when I was trying to allow `box` and `Box` for necessity—some copies seem to have survived the merge, so definitely feel free to delete them!

**Comment by benbrastmckie** [comment]
OK great! The null state strategy has its own advantages, so by no means wasted effort. It is actually more general and can even permit modal sentences to occur as antecedents of counterfactuals. The same is true for counterfactuals since they should also be verified by the null state if true and by nothing otherwise.

**Comment by benbrastmckie** [comment]
I updated the new branch `add_modals` to reflect the current changes. I'll working in `fix_print` and they we can merge both into master when they are working.

**Comment by benbrastmckie** [comment]
I'm having trouble finding what is producing the first two test print statements. I think I added these and will try to remember to add TEST whenever including testing print statements. But if you get a chance to see where these are coming from I can seem to find them.

**Comment by benbrastmckie** [comment]
Never mind, I found it!

**Comment by benbrastmckie** [comment]
Hey just finished testing and it is working great! By including modals we are in a position to check to see if `\\top \\boxright A` is in fact equivalent to `\\Box A`. The right-to-left direction goes through very quickly, but the left-to-right direction gets killed by the mit server. I don't think this is a big problem for what we have, and may even reveal something about Z3, or perhaps lead to some further improvement down the road. In any case, I'm going to try to raise this issue with the right person at some point. It's a nice clean example. I think this may also be related to the fact that the K axiom does not go through when articulated in terms of `\\top`. I feel like these are potentially interesting leads.

As for the modal logic, it gets everything we should expect when articulated in terms of `\\Box`. The entailment from `\\Box (A \\rightarrow B)` to `A \\boxright B` also goes through easily, though it crashes the server when trying to find a countermodel for the converse direction. This is also interesting, and something I'll bring up with the other cases once the Z3 guru appears.

In any case, I'm very pleased with how this is coming together. I'll try to work on releasing and testing v0.2 so that it can be easily shared.

**Comment by mbuit82** [comment]
Revisiting the earlier case that was causing trouble before, here's a new model: 

```There is a 3-model of:

1. (\Box A \vee \Box B)
2. \neg (A \wedge B)

Possible states:
  #b000 = □
  #b001 = a
  #b100 = c
  #b101 = a.c (world)

The evaluation world is a.c:
  B  (True in a.c)
  A  (Not true in a.c)

1.  (\Box A \vee \Box B)  (True in a.c)
    \Box A  (False in a.c)
      |A| = < ∅, {a} >  (False in a.c)
    \Box B  (True in a.c)
      |B| = < {a, a.c, c}, ∅ >  (True in a.c)

2.  \neg (A \wedge B)  (True in a.c)
    (A \wedge B)  (False in a.c)
      |A| = < ∅, {a} >  (False in a.c)
      |B| = < {a, a.c, c}, ∅ >  (True in a.c)```

I think it makes more sense but `rec_print` seems to be giving less information now

**Comment by benbrastmckie** [comment]
I think the printing looks great. What information is it missing?

**Comment by mbuit82** [comment]
Compare this output: 

```
There is a 3-model of:

1. (\Box A \vee \Box B)
2. \neg (A \wedge B)

Possible states:
  #b000 = □
  #b001 = a
  #b100 = c
  #b101 = a.c (world)

The evaluation world is a.c:
  B  (True in a.c)
  A  (Not true in a.c)

1.  (\Box A \vee \Box B)  (True in a.c)
    |(\Box A \vee \Box B)| = < {□}, ∅ >  (True in a.c)
    \Box A  (False in a.c)
      |\Box A| = < ∅, {□} >  (False in a.c)
      |A| = < ∅, {a} >  (False in a.c)
    \Box B  (True in a.c)
      |\Box B| = < {□}, ∅ >  (True in a.c)
      |B| = < {a, a.c, c}, ∅ >  (True in a.c)

2.  \neg (A \wedge B)  (True in a.c)
    |\neg (A \wedge B)| = < {a}, ∅ >  (True in a.c)
    (A \wedge B)  (False in a.c)
      |(A \wedge B)| = < ∅, {a} >  (False in a.c)
      |A| = < ∅, {a} >  (False in a.c)
      |B| = < {a, a.c, c}, ∅ >  (True in a.c)
```
It gives the absolute value for all propositions (can be made to be only extensional, or only atomic as before). Which one do you prefer?

**Comment by benbrastmckie** [comment]
Oh I see. The extra information is not super important for modal and counterfactual sentences, but is important for complex sentences with lots of extensional operators (could also include nonextensional operators). For instance, it is nice to see the verifiers for something like `(A \vee (B \wedge C))`. However, the first print statements are redundant with the second line; all we need is whatever is generating the second line. Hope that makes sense.

**Comment by mbuit82** [comment]
Ah yes I see. Which one do you prefer, the top style or the bottom style?

**Comment by benbrastmckie** [comment]
The bottom one is great, e.g., ` |\neg (A \wedge B)| = < {a}, ∅ >  (True in a.c)`. Always knowing what the verifiers and falsifiers are will be convenient for complex propositions even if they don't help too much for these simple cases.

**Comment by mbuit82** [comment]
Sounds good! How does this output look?

```
There is a 3-model of:

1. neg A
2. (A boxright (B vee C))
3. \neg (A boxright B)
4. \neg (A boxright C)

Possible states:
  #b000 = □
  #b001 = a (world)
  #b010 = b (world)
  #b100 = c (world)

The evaluation world is b:
  B  (True in b)
  A, C  (Not true in b)

1.  |\neg A| = < {b}, {a, c} >  (True in b)
    |A| = < {a, c}, {b} >  (False in b)

2.  |(A boxright (B vee C))| = < {a, b, c}, ∅ >  (True in b)
    A-alternatives to b = {a, c}
    |A| = < {a, c}, {b} >  (False in b)
      |(B vee C)| = < {a, b, c}, ∅ >  (True in a)
        |B| = < {b, c}, {a} >  (False in a)
        |C| = < {a}, {b, c} >  (True in a)
      |(B vee C)| = < {a, b, c}, ∅ >  (True in c)
        |B| = < {b, c}, {a} >  (True in c)
        |C| = < {a}, {b, c} >  (False in c)

3.  |\neg (A boxright B)| = < ∅, {a, b, c} >  (False in b)
    |(A boxright B)| = < {a, b, c}, ∅ >  (True in b)
      A-alternatives to b = {a, c}
      |A| = < {a, c}, {b} >  (False in b)
        |B| = < {b, c}, {a} >  (False in a)
        |B| = < {b, c}, {a} >  (True in c)

4.  |\neg (A boxright C)| = < ∅, {a, b, c} >  (False in b)
    |(A boxright C)| = < {a, b, c}, ∅ >  (True in b)
      A-alternatives to b = {a, c}
      |A| = < {a, c}, {b} >  (False in b)
        |C| = < {a}, {b, c} >  (True in a)
        |C| = < {a}, {b, c} >  (False in c)
```

**Comment by benbrastmckie** [comment]
Looks great!!

**Comment by benbrastmckie** [comment]
I was going to remove the `if 'top' in...` clause from `true_at` in the following:
```
        if len(sentence) == 1:
            sent = sentence[0]
            if 'top' in str(sent)[0]:
                raise ValueError('This is raised in principle when top is a proposition.')
                # if top is a sentence letter, its constraint is already in the model.
                # It wouldn't hurt to add it again I think in principle, but if there's something
                # else that should go here when top is passed in by itself then it would go here
                # return ForAll(x, And(verify(x, sent),Not(falsify(x, sent)))) # this is the top constraint
                # NOTE: I (M) think this issue was resolved
            return Exists(x, And(is_part_of(x, eval_world), verify(x, sent)))
```
However, I think it might be slightly better to have the following:
```
        if len(sentence) == 1:
            sent = sentence[0]
            if 'top' not in str(sent)[0]:
                return Exists(x, And(is_part_of(x, eval_world), verify(x, sent)))
```
That way when `top` is the sentence letter in question, it doesn't add an extra Z3 constraint (since `top` will already be required to be verified by everything, making the extra constraint redundant). Just wanted to run this by @mbuit82 in case you had any worries.

**Comment by benbrastmckie** [comment]
I think this issues have been resolved.
