### ISSUE TITLE
Optimization: removing quantifiers

### ISSUE THREAD

**Issue by mbuit82** [benbrastmckie/ModelChecker#31]
Using Z3 for something else I realized the set of constraints I had seemed to run faster if I added a constraint on each element of the domain instead of adding one constraint with a universal quantifier (e.g., if I need the constraint ForAll(x, func(x)), and there are 8 elements that x could refer to, I instead added a constraint func(a) for each 'a' that x could be). For context there was about 50 elements in the relevant domain, so I added about 50 constraints instead of 1 universally quantified one, and nonetheless it ran faster (faster as in with the universal quantifiers it wouldn't terminate but without them it took 20 seconds—I wasn't keeping track of all the modifications I was making so I'm not certain that just the quantifiers change is what caused such a drastic difference but I figured it probably helped). 

Since with small values of N there are never more than a small number of bitvectors in the domain that a universal quantifier is quantifying over, I thought maybe removing universal quantifiers in our code could help. I made a new branch called `no_quantifiers` to try this out in. To make implementation as easy as possible my idea was to keep the existing text of `semantics.py` the same, only not importing Z3's `ForAll` and instead defining it in the code as a python function that makes a really long `And()` constraint with each conjunct being a constraint for an element in the domain. I made a separate little file (now in the code as `no_quantifiers_original_test.py`) that has the code that I used to make and test the new function; running that you'll see it is slightly faster than the universal quantifier for quantifying over three variables, so maybe the universal quantifiers do make things slower. And it can make sense that removing the universal quantifier makes things faster because from what I understand Z3 has a pattern based approach to quantifiers, not a brute force approach (since I think it assumes the domains aren't necessarily small, like they are for us). 

I then tried to see if I could put that new function in `semantics.py` to remove Z3 quantifiers in our code. Hit some bumps but I think fixed, just need to get rid of existential quantifiers now (which should actually be pretty easy because I remember reading somewhere that when you put an existential in Z3 it actually is the same as not putting an existential or something like that). 

On a related note, I remember you wanted to have constraints print to another file that the user could then run. I didn't think that would be possible bc it would print it as a string but you'd need Z3 objects to run the file, but it seems it may be possible with the eval() and exec() methods—I used them in this code; you might want to play around with them if that's still an idea you're interested in

**Comment by benbrastmckie** [comment]
I'm going to close this issue to consolidate it with Issue #19 and open a new issue for printing constraints to a file.

**Comment by benbrastmckie** [comment]
I change my mind... removing the quantifiers definitely deserves to be its own issue. I got something to run using substitution instead of lambda abstractors. Here are the definitions:
```
def ForAllFinite(bvs, formula):
    """
    generates constraints by substituting all possible bitvectors for the variables in the formula
    before taking the conjunction of those constraints
    """
    constraints = []
    if not isinstance(bvs, list):
        bvs = [bvs]
    bv_test = bvs[0]
    temp_N = bv_test.size()
    num_bvs = 2 ** temp_N
    if len(bvs) == 1:
        bv = bvs[0]
        for i in range(num_bvs):
            substituted_formula = substitute(formula, (bv, BitVecVal(i, temp_N)))
            constraints.append(substituted_formula)
    else:
        bv = bvs[0]
        remaining_bvs = bvs[1:]
        reduced_formula = ForAllFinite(remaining_bvs, formula)
        for i in range(num_bvs):
            substituted_reduced_formula = substitute(reduced_formula, (bv, BitVecVal(i, temp_N)))
            constraints.append(substituted_reduced_formula)
    return And(constraints)

def ExistsFinite(bvs, formula):
    """
    generates constraints by substituting all possible bitvectors for the variables in the formula
    before taking the disjunction of those constraints
    """
    constraints = []
    if not isinstance(bvs, list):
        bvs = [bvs]
    bv_test = bvs[0]
    temp_N = bv_test.size()
    num_bvs = 2 ** temp_N
    if len(bvs) == 1:
        bv = bvs[0]
        for i in range(num_bvs):
            substituted_formula = substitute(formula, (bv, BitVecVal(i, temp_N)))
            constraints.append(substituted_formula)
    else:
        bv = bvs[0]
        remaining_bvs = bvs[1:]
        reduced_formula = ForAllFinite(remaining_bvs, formula)
        for i in range(num_bvs):
            substituted_reduced_formula = substitute(reduced_formula, (bv, BitVecVal(i, temp_N)))
            constraints.append(substituted_reduced_formula)
    return Or(constraints)
```
Although it finds models when using `ForAllFinite`, the models it finds are not correct. It doesn't seem to find any models at all using `ExistsFinite`. I'm not too sure what to make of this as it seems to be generating the correct constraints.

**Comment by benbrastmckie** [comment]
I tried cutting and pasting the code above from the `no_quantifiers` branch straight into `master` and it seems to work great with `ForAllFinite` turned on but not so for `ExistsFinite`. In any case, there is a massive gain in performance, and I'll keep poking to see if I can sort out why `ExistsFinite` doesn't work.

**Comment by benbrastmckie** [comment]
I got this working great. It's really fast, where running `pytest` in the `ModelChecker\Code\` directory passes 120 examples in less than the time it used to take for just one. The only remaining questions are:

1. How does `Lambda` work in Z3 and how does that strategy compare (I couldn't get them to work so used `substitute` instead).
2. It seems that something else changed in the `no_quantifiers` branch that made it stop working. I couldn't figure out what this was.

In any case, thanks for taking the initiative on getting this ball rolling. It has made the model-checker much more powerful and easy to use. I will turn my attention towards updating the documentation which shouldn't take me too long.
