### ISSUE TITLE
separate prefix algorithm from semantics

### ISSUE THREAD

**Issue by benbrastmckie** [benbrastmckie/ModelChecker#38]
I thought it might be helpful to open an issue for this. The aim is to refactor the prefix function so as not to depend on which operators the language includes, remaining agnostic about the semantics and even arity for those operators. Here is a sketch what I was thinking:

- define `find_op_and_args(string, parens_number=0, triggered=False)` algorithm:
- if `triggered` and `parens_number=0`, then return
- if first character is a left parentheses:
  - cut and store the first character in `left_arg`
  - set `parens_number =+ 1`
  - run `find_op_and_args(string, parens_number, true)`
- if first character is a right parentheses:
  - cut and store the first character in `left_arg`
  - set `parens_number =- 1`
  - run `find_op_and_args(string, parens_number, triggered)`
- else:
  - cut and store first character in `left_arg`
  - run `find_op_and_args(string, parens_number, triggered)`
- define `prefix` algorithm:
- `infix_sentence` takes one of three forms:
  - `(left_arg \op right_arg)` in the case of a binary operator
  - `\op single_arg` in the case of a unary operator
  - `\op` in the case of a zero-place operator
- converting to prefix form is easy for the latter two forms
- if the first form, then the algorithm proceeds by:
  - delete first left parentheses
  - if the next character is a space, delete and check the next character
  - if the next character is a parentheses, then set `left_arg, op, right_arg = find_op_and_args(infix_sentence)`
  - else:
    - store everything up to first `\` as `left_arg`
    - store the next word as `op`
    - store the remainder minus the final parentheses as `right_arg`
  - return `[op, prefix(left_arg), prefix(right_arg)]`

There may well be ways to improve on this but thought this might help to provide a way in.

**Comment by benbrastmckie** [comment]
I almost got `pure_prefix` to work. It runs but has errors for complicated cases. I can't quite see what the issue is. If you have a chance to take a look I'd be curious to know if you can spot the error. Seems like it is very close.

**Comment by benbrastmckie** [comment]
Never mind I got it!

**Comment by benbrastmckie** [comment]
I made all of the syntax functions methods of the ModelSetup class. If it makes more sense, we could move some of these to a syntax module, though right now no module is imported by `hidden_things.py`. I suspect elements are still missing from the syntax functions from before, in particular, I did not include the `return [Const(token, AtomSort)]` though commented out where I think it should go. I also made some changes to the `Operator` class to fix the linter errors I was getting and updated the TODOs. Definitely making progress!

**Comment by mbuit82** [comment]
Looks good! I ran into some snags with a sentence like `(\\neg B \\wedge \\neg D)`, but I think it's on the right track. I added some things (like the `Const` bit). It may make more sense to put all the helpers in a new syntax module, but that's a pretty small detail that could be done later. 

I cleaned up the new approach so that now it can find models given an input—it won't print nicely because those methods haven't been refactored in yet. In this approach I used the old prefix function, except now the set of unary operators does not come from the `syntax` module, rather it comes from all operators with arity 1 in the `ModelSetup` object. So now there should be no issues in the syntax so long as a user specifies and adds that operator to the `ModelSetup` object they instantiate in the code, but the complete separation of syntax and semantics isn't achieved

**Comment by benbrastmckie** [comment]
I missed the case for unary operators in the `left_op_right` function and now seems to be working in place of the prefix function from `syntax.py`. As far as moving helper functions around, I was thinking maybe it would be nice to leave `prefix()` as a method but then move all of the helper functions it need into a separate module. Let me know if you think that makes sense and if you think we can close this issue.

**Comment by mbuit82** [comment]
Ahh that makes sense, perfect—I agree with leaving prefix and moving the rest!

**Comment by benbrastmckie** [comment]
Ok great. I moved the helpers to a new module. Unless there are tons, or there is a reason to divide them, I was thinking all helpers for `hidden_things.py` would belong to the same module. I imagine some of the other syntactic helps could also be moved into there. I'm going to close this issue for now.

**Comment by mbuit82** [comment]
I ran into an issue with the following prefix sentence: 

```
"((A \\rightarrow (B \\wedge C)) \\wedge D)"
```

It said `ValueError: Expected an operator following D` (it was an error in `left_op_right`

**Comment by mbuit82** [comment]
I ran into an issue with the following prefix sentence: 

```
"((A \\rightarrow (B \\wedge C)) \\wedge D)"
```

It said `ValueError: Expected an operator following D` (it was an error in `left_op_right`

**Comment by benbrastmckie** [comment]
I refactored the prefix algorithm and feeling much better about it. Seems to be working, but will set up a unit test to confirm that it's working in all types of cases.
