### ISSUE TITLE
true conclusion and false premise models

### ISSUE THREAD

**Issue by benbrastmckie** [benbrastmckie/ModelChecker#49]
I added primitive operators for identity, essence, and ground. I also added defined operators for essence and ground. There are some strange results where it finds models in which a premise is false or in which a conclusion is true. This shouldn't be possible if everything is working, so not sure what is going wrong.

This was an issue that came up before and has just reoccurred. I never managed to figure out what was going wrong back then, but hopefully now if will be easier to sort out. I set up a bunch of cases in `test_example.py`. Curious to know if you have any sense of what is going on here.

**Comment by mbuit82** [comment]
Wait so currently `DefinedOperator` is not working and the fix was to define the operators as primitives? Just to make sure I'm understanding this issue

**Comment by benbrastmckie** [comment]
That `DefinedOperator` is not working means that I can't test the other true-conclusion and false-premise examples that I found before. It is promising that the one example given above that I could test (since it doesn't need `DefinedOperator`) is now working. Basically this issue can be ignored until after `DefinedOperator` is working.

**Comment by benbrastmckie** [comment]
I'm very curious how the change you mentioned today about directly calling `evaluate_at_model` to check truth values may help to avoid getting true conclusions and false premises. Seems like this could be implemented for the other non-extensional operators as well. I think it would be good to develop this on a branch without merging into master so that we can switch between to see if this fixes the true conclusion/ false premise problem, solving the mystery.

**Comment by benbrastmckie** [comment]
These seem to mostly have resolved with the exception of the following:
```
# premises = ["A", "(B \\essence A)"]
# conclusions = ["\\neg B"]
```
I think this is because DefinedOperator is expecting propositions instead of sentences.
